{
 "title": "Validator Stats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Val Rewards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "My Rewards per stake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(val_stat_rewards{validator=\"18\"}[$__range]) / (val_stat_stakeActual and count_values without() (\"validator\", val_id))",
     "legendFormat": "{{validator}}"
    },
    {
     "expr": "avg(increase(val_stat_rewards[$__range])/val_stat_stakeActual)",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Validator Stake",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(val_stat_rewards[24h])/val_stat_stakeActual",
     "legendFormat": "__auto"
    },
    { "expr": "val_stat_staked", "legendFormat": "__auto" },
    { "expr": "val_stat_delegated", "legendFormat": "__auto" },
    {
     "expr": "val_stat_delegated - val_stat_staked",
     "legendFormat": "__auto"
    },
    {
     "expr": "val_stat_staked*11 - val_stat_delegated",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Val Reward Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "increase(val_stat_rewards[$__range])/val_stat_stakeActual",
     "legendFormat": "{{validator}}"
    },
    { "expression": "A", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Val Self Stake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 27 },
   "targets": [
    { "expr": "val_stat_locked", "legendFormat": "{{validator}}" },
    { "expression": "A", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "Val Delegation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 35 },
   "targets": [
    { "expr": "val_stat_delegated", "legendFormat": "{{validator}}" },
    { "expression": "A", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  {
   "title": "interval average lemx distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": " sum(increase(val_stat_rewards[$__range]))",
     "legendFormat": "{{validator}}"
    },
    { "expression": "A", "reducer": "mean", "settings": { "mode": "dropNN" }, "type": "reduce" }
   ]
  },
  { "title": "myVal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Pending Rewards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "val_pending_rewards", "legendFormat": "  " }
   ]
  },
  {
   "title": "Personal Stake",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "LEMX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "val_stake_lemx", "legendFormat": " " }
   ]
  },
  {
   "title": "Investor Stake",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "LEMX" } },
   "targets": [
    {
     "expr": "val_delegated_lemx - val_stake_lemx",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Epoch Validator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 52 },
   "targets": [
    { "expr": "val_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Validator Run Time in days",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - val_start_time) / (3600*24)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "8*rate(node_network_transmit_bytes_total{device=\"enp2s0\"}[$__rate_interval])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Rx Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "8*rate(node_network_receive_bytes_total{device=\"enp2s0\"}[$__rate_interval])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Pending Rewards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(val_pending_rewards) * avg(lemx_quote_price)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Investor Value",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " avg(lemx_quote_price) * avg(val_delegated_lemx - val_stake_lemx)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Space Left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "LEMX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "11*val_stake_lemx - val_delegated_lemx",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 56 },
   "targets": [
    { "expr": "p2p_peers", "legendFormat": " " }
   ]
  },
  {
   "title": "LemChain DB Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_size", "legendFormat": " " }
   ]
  },
  {
   "title": "/extra usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/extra\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/extra\",fstype!=\"rootfs\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Inserts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_inserts{type=\"mean-rate\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Personal + 35%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "LEMX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "val_stat_stakeActual and count_values without() (\"validator\", val_id)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Personal Stake Value",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(val_stake_lemx) *  avg(lemx_quote_price) ",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "% Stake",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "val_delegated_lemx / val_total_stake",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rewards Average",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 60 },
   "targets": [
    {
     "expr": "increase(val_pending_rewards[$__range])",
     "legendFormat": " LEMX"
    }
   ]
  },
  {
   "title": "Rewards Average",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "increase(val_pending_rewards[$__range])*scalar(avg(lemx_quote_price))",
     "legendFormat": " LEMX"
    }
   ]
  },
  {
   "title": "??Prev Reward per Token??",
   "type": "stat",
   "description": "No Idea what this metrics is ...",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "LEMX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "val_prev_rewards_per_token", "legendFormat": " " }
   ]
  },
  {
   "title": "LEMX Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(lemx_quote_price)", "legendFormat": " " }
   ]
  },
  {
   "title": "Val Rank",
   "type": "stat",
   "description": "Ranking in Total Delegation",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "val_rank", "legendFormat": " " }
   ]
  },
  {
   "title": "Validator Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "val_listening", "legendFormat": " " }
   ]
  },
  {
   "title": "Wallet Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "val_wallet_status", "legendFormat": " " }
   ]
  },
  {
   "title": "Invalid TX Pool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_invalid{type=\"one-minute\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total Vals",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "val_total_active", "legendFormat": " " }
   ]
  },
  { "title": "LemonChain Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "val_current_block_count", "legendFormat": " " }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "val_current_epoch_count", "legendFormat": " " }
   ]
  },
  {
   "title": "Total Stake",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 70 },
   "targets": [
    { "expr": "val_total_stake", "legendFormat": " " }
   ]
  },
  {
   "title": "Chain Head",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 13, "y": 70 },
   "targets": [
    { "expr": "chain_head_block", "legendFormat": "Block" },
    { "expr": "chain_head_header", "legendFormat": "Header" },
    { "expr": "chain_head_receipt", "legendFormat": "Receipt" }
   ]
  },
  {
   "title": "Execution",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_execution{type=\"mean-rate\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rate(val_current_block_count[1h])*60",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Cur Epoch duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "2 + (time() - max_over_time(timestamp(changes(val_current_epoch_count[2m]) > 0)[24h:5s]))/60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_validation{type=\"mean-rate\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Queued TX Pool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "val_tx_pool_queued", "legendFormat": " " }
   ]
  },
  {
   "title": "Valid TX Pool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_valid{type=\"one-minute\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Underpriced TX Pool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_underpriced{type=\"one-minute\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Chain Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "val_chain_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Epochs per hour",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "rate(val_current_epoch_count[24h])*3600",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Epoch Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "1/(rate(val_current_epoch_count[24h])*60)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Local TX Pool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "txpool_local", "legendFormat": " " }
   ]
  },
  {
   "title": "Pending TX Pool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "val_tx_pool_pending", "legendFormat": " " }
   ]
  },
  {
   "title": "Gas (Gwei)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 82 },
   "targets": [
    { "expr": "val_current_gas", "legendFormat": " " }
   ]
  },
  {
   "title": "Max Priority Gas (Gwei)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 82 },
   "targets": [
    { "expr": "val_current_max_priority_gas", "legendFormat": " " }
   ]
  },
  { "title": "CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "CPU Load | $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 88 },
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  { "title": "Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 5, "w": 10, "x": 6, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "Net IN (24h)",
     "type": "stat",
     "description": "Network traffic in the last hour",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$node\"}[24h]))"
      }
     ]
    },
    {
     "title": "Network Traffic Basic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 8, "w": 15, "x": 4, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "recv {{device}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "trans {{device}} "
      }
     ]
    },
    {
     "title": "Net Out (24h)",
     "type": "stat",
     "description": "Network traffic out the last hour",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$node\"}[24h]))"
      }
     ]
    }
   ]
  },
  {
   "title": "File System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Root FS Used",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "Disk Space Used Basic",
     "type": "timeseries",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 5, "w": 13, "x": 3, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IOps",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 11, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 11, "x": 11, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Successfully written bytes"
      }
     ]
    },
    {
     "title": "Disk I/O Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 173 },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"} [$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "I/O Utilization",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"} [$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NVME Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage Used by Device",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "nvme_percentage_used_ratio", "legendFormat": "{{device}}" }
     ]
    },
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "nvme_temperature_celsius", "legendFormat": "{{device}}" }
     ]
    },
    {
     "title": "NVM Subsystem Reliability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "Misc" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nvme_critical_warning", "legendFormat": "nvme0n1" }
     ]
    },
    {
     "title": "Controller Busy Time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nvme_controller_busy_time_seconds_total",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  }
 ]
}